import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
    <body>
      <header className="header">
        <div className="container">
          <a href="#" className="logo">Grava</a>
          <nav className="nav">
            <a href="#" className="nav-link">Inicio</a>
            <a href="#" className="nav-link">Pokemon</a>
            <a href="#" className="nav-link">Nosotros</a>
            <a href="#" className="nav-link">Contacto</a>
          </nav>
        </div>
      </header>
      <main>{children}</main>
      <footer className="footer">
          <div className="container">
            <div className="footer-content">
              <div className="info">
                <h2 className="titulo">Todos los derechos reservados</h2>
                <p>Direccion 123</p>
                <p>11 2030-2222</p>
              </div>
              <div className="iconos">
                <a href="#"><span className="icono">FB</span></a>
                <a href="#"><span className="icono">IG</span></a>
                <a href="#"><span className="icono">X</span></a>
              </div>
            </div>
          </div>
        </footer>
    </body>
  </html>
  );
}
